#!/usr/bin/env bash

# Ensure if we have to install any packages for deps we can.
apt-get update

ensureLicenser
ensureProtoc
ensurePyDeps

set -ex

find envoy_pkg common -type f -name '*.py' | grep -v 'envoy/src' | xargs yapf --in-place

# Generate Protos
find api -type f -name '*.proto' | xargs protoc --go_out=.

# Apply Licenses
scratch/licenser apply -r "Tetrate"
