#!/bin/bash
set -ex

find envoy_pkg common -type f -name '*.py' -user "${USER}" | grep -v 'envoy/src' | xargs yapf --in-place

# Generate Protos
find api -type f -name '*.proto' | xargs protoc --go_out=.

# Apply Licenses
licenser apply -r "Tetrate"
