#!/bin/bash

# Install Proto compiler
wget https://github.com/protocolbuffers/protobuf/releases/download/v3.8.0/protoc-3.8.0-linux-x86_64.zip
unzip protoc-3.8.0-linux-x86_64.zip -d protoc
sudo mv protoc/bin/* /usr/bin/
sudo mv protoc/include/* /usr/include/
rm -rf protoc*

# Install Golang Proto generator
go get -u github.com/golang/protobuf/protoc-gen-go@v1.3.2
