#!/usr/bin/env bash

# Ensure if we have to install any packages for deps we can.
apt-get update

ensureLicenser
ensurePyDeps

set -ex

# Currently, this just includes format checking, eventually includes lint etc.
find envoy_pkg common -type f -name '*.py' | grep -v 'envoy/src' | xargs yapf --diff

flake8 envoy_pkg common

scratch/licenser verify -r .
