#!/bin/bash
set -ex

# Currently, this just includes format checking, eventually includes lint etc.
find envoy_pkg common -type f -name '*.py' -user "${USER:-$(id -u -n)}" | grep -v 'envoy/src' | xargs yapf --diff

flake8 --ignore E402,E501 envoy_pkg common

licenser verify -r .
