#!/usr/bin/env bash

# Ensure if we have to install any packages for deps we can.
apt-get update

ensureLicenser
ensureProtoc

set -ex

if [ "$(git status --porcelain -uno)" != "" ]; then
  echo "Please run lint from a clean branch."
  exit 10
fi

# Ensure Protos are generated and up-to-date
find api -type f -name '*.proto' | xargs protoc --go_out=.
scratch/licenser apply -r "Tetrate" &> /dev/null
if [ "$(git status --porcelain -uno)" != "" ]; then
  echo "The following Protos need to be regenerated:"
  git status --porcelain -v -uno
  git --no-pager diff
  exit 11
fi
