#!/bin/bash

# Ensure Protos are generated and up-to-date
find api -type f -name '*.proto' | xargs protoc --go_out=.
licenser apply -r "Tetrate" &> /dev/null
if [ "$(git status --porcelain -uno)" != "" ]; then
    echo "The following Protos need to be regenerated:"
    git status --porcelain -v -uno
    git --no-pager diff
    exit 1
fi
