// Copyright 2019 Tetrate
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/manifest.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Compliance int32

const (
	Compliance_FIPS_1402 Compliance = 0
)

var Compliance_name = map[int32]string{
	0: "FIPS_1402",
}

var Compliance_value = map[string]int32{
	"FIPS_1402": 0,
}

func (x Compliance) String() string {
	return proto.EnumName(Compliance_name, int32(x))
}

func (Compliance) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{0}
}

type OperatingSystemFamilyName int32

const (
	OperatingSystemFamilyName_DEBIAN_FAMILY  OperatingSystemFamilyName = 0
	OperatingSystemFamilyName_RHEL_FAMILY    OperatingSystemFamilyName = 1
	OperatingSystemFamilyName_DARWIN_FAMILY  OperatingSystemFamilyName = 2
	OperatingSystemFamilyName_WINDOWS_FAMILY OperatingSystemFamilyName = 3
)

var OperatingSystemFamilyName_name = map[int32]string{
	0: "DEBIAN_FAMILY",
	1: "RHEL_FAMILY",
	2: "DARWIN_FAMILY",
	3: "WINDOWS_FAMILY",
}

var OperatingSystemFamilyName_value = map[string]int32{
	"DEBIAN_FAMILY":  0,
	"RHEL_FAMILY":    1,
	"DARWIN_FAMILY":  2,
	"WINDOWS_FAMILY": 3,
}

func (x OperatingSystemFamilyName) String() string {
	return proto.EnumName(OperatingSystemFamilyName_name, int32(x))
}

func (OperatingSystemFamilyName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{1}
}

type OperatingSystemName int32

const (
	OperatingSystemName_UBUNTU OperatingSystemName = 0
	OperatingSystemName_DEBIAN OperatingSystemName = 1
	OperatingSystemName_CENTOS OperatingSystemName = 2
	OperatingSystemName_RHEL   OperatingSystemName = 3
	OperatingSystemName_MACOS  OperatingSystemName = 4
)

var OperatingSystemName_name = map[int32]string{
	0: "UBUNTU",
	1: "DEBIAN",
	2: "CENTOS",
	3: "RHEL",
	4: "MACOS",
}

var OperatingSystemName_value = map[string]int32{
	"UBUNTU": 0,
	"DEBIAN": 1,
	"CENTOS": 2,
	"RHEL":   3,
	"MACOS":  4,
}

func (x OperatingSystemName) String() string {
	return proto.EnumName(OperatingSystemName_name, int32(x))
}

func (OperatingSystemName) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{2}
}

// Builds must be uniquely addressable from the top level so that they can be used to look up the location of binaries.
// Format: filter_profile(-compliance_profile):envoy_version/operating_system-operating_system_version
// Examples:
//   - istio-fips1402:1.10.1/ubuntu-16.04
//   - standard:nightly/debian-8
type Manifest struct {
	ManifestVersion string `protobuf:"bytes,1,opt,name=manifest_version,json=manifestVersion,proto3" json:"manifest_version,omitempty"`
	// Key is composite key of the value's filter_profile and compliance_profile
	// Note: compliance_profile is optional
	// Format: filter_profile(-compliance_profile)
	Flavors              map[string]*Flavor `protobuf:"bytes,2,rep,name=flavors,proto3" json:"flavors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Manifest) Reset()         { *m = Manifest{} }
func (m *Manifest) String() string { return proto.CompactTextString(m) }
func (*Manifest) ProtoMessage()    {}
func (*Manifest) Descriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{0}
}

func (m *Manifest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Manifest.Unmarshal(m, b)
}
func (m *Manifest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Manifest.Marshal(b, m, deterministic)
}
func (m *Manifest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Manifest.Merge(m, src)
}
func (m *Manifest) XXX_Size() int {
	return xxx_messageInfo_Manifest.Size(m)
}
func (m *Manifest) XXX_DiscardUnknown() {
	xxx_messageInfo_Manifest.DiscardUnknown(m)
}

var xxx_messageInfo_Manifest proto.InternalMessageInfo

func (m *Manifest) GetManifestVersion() string {
	if m != nil {
		return m.ManifestVersion
	}
	return ""
}

func (m *Manifest) GetFlavors() map[string]*Flavor {
	if m != nil {
		return m.Flavors
	}
	return nil
}

type Flavor struct {
	// This is duplicated in order to make flavor easier to sort
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Filter profile is the name of the collection of filters
	// E.g. standard, minimal, istio
	FilterProfile string `protobuf:"bytes,2,opt,name=filter_profile,json=filterProfile,proto3" json:"filter_profile,omitempty"`
	// All filters available in this flavor
	Filters     []string     `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	Compliances []Compliance `protobuf:"varint,4,rep,packed,name=compliances,proto3,enum=api.Compliance" json:"compliances,omitempty"`
	// Key is Envoy version
	Versions             map[string]*Version `protobuf:"bytes,5,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Flavor) Reset()         { *m = Flavor{} }
func (m *Flavor) String() string { return proto.CompactTextString(m) }
func (*Flavor) ProtoMessage()    {}
func (*Flavor) Descriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{1}
}

func (m *Flavor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flavor.Unmarshal(m, b)
}
func (m *Flavor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flavor.Marshal(b, m, deterministic)
}
func (m *Flavor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flavor.Merge(m, src)
}
func (m *Flavor) XXX_Size() int {
	return xxx_messageInfo_Flavor.Size(m)
}
func (m *Flavor) XXX_DiscardUnknown() {
	xxx_messageInfo_Flavor.DiscardUnknown(m)
}

var xxx_messageInfo_Flavor proto.InternalMessageInfo

func (m *Flavor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Flavor) GetFilterProfile() string {
	if m != nil {
		return m.FilterProfile
	}
	return ""
}

func (m *Flavor) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *Flavor) GetCompliances() []Compliance {
	if m != nil {
		return m.Compliances
	}
	return nil
}

func (m *Flavor) GetVersions() map[string]*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

type Version struct {
	// This duplicated in order to make version easier to sort
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Builds               []*Build `protobuf:"bytes,2,rep,name=builds,proto3" json:"builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{2}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Version) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type Build struct {
	OperatingSystemFamily *OperatingSystemFamily `protobuf:"bytes,1,opt,name=operating_system_family,json=operatingSystemFamily,proto3" json:"operating_system_family,omitempty"`
	DownloadLocationUrl   string                 `protobuf:"bytes,2,opt,name=download_location_url,json=downloadLocationUrl,proto3" json:"download_location_url,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{3}
}

func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (m *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(m, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetOperatingSystemFamily() *OperatingSystemFamily {
	if m != nil {
		return m.OperatingSystemFamily
	}
	return nil
}

func (m *Build) GetDownloadLocationUrl() string {
	if m != nil {
		return m.DownloadLocationUrl
	}
	return ""
}

type OperatingSystemFamily struct {
	Name                 OperatingSystemFamilyName `protobuf:"varint,1,opt,name=name,proto3,enum=api.OperatingSystemFamilyName" json:"name,omitempty"`
	Children             []*OperatingSystem        `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *OperatingSystemFamily) Reset()         { *m = OperatingSystemFamily{} }
func (m *OperatingSystemFamily) String() string { return proto.CompactTextString(m) }
func (*OperatingSystemFamily) ProtoMessage()    {}
func (*OperatingSystemFamily) Descriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{4}
}

func (m *OperatingSystemFamily) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatingSystemFamily.Unmarshal(m, b)
}
func (m *OperatingSystemFamily) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatingSystemFamily.Marshal(b, m, deterministic)
}
func (m *OperatingSystemFamily) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatingSystemFamily.Merge(m, src)
}
func (m *OperatingSystemFamily) XXX_Size() int {
	return xxx_messageInfo_OperatingSystemFamily.Size(m)
}
func (m *OperatingSystemFamily) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatingSystemFamily.DiscardUnknown(m)
}

var xxx_messageInfo_OperatingSystemFamily proto.InternalMessageInfo

func (m *OperatingSystemFamily) GetName() OperatingSystemFamilyName {
	if m != nil {
		return m.Name
	}
	return OperatingSystemFamilyName_DEBIAN_FAMILY
}

func (m *OperatingSystemFamily) GetChildren() []*OperatingSystem {
	if m != nil {
		return m.Children
	}
	return nil
}

type OperatingSystem struct {
	Name                 OperatingSystemName `protobuf:"varint,1,opt,name=name,proto3,enum=api.OperatingSystemName" json:"name,omitempty"`
	Versions             []string            `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OperatingSystem) Reset()         { *m = OperatingSystem{} }
func (m *OperatingSystem) String() string { return proto.CompactTextString(m) }
func (*OperatingSystem) ProtoMessage()    {}
func (*OperatingSystem) Descriptor() ([]byte, []int) {
	return fileDescriptor_346685e380de5b1f, []int{5}
}

func (m *OperatingSystem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatingSystem.Unmarshal(m, b)
}
func (m *OperatingSystem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatingSystem.Marshal(b, m, deterministic)
}
func (m *OperatingSystem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatingSystem.Merge(m, src)
}
func (m *OperatingSystem) XXX_Size() int {
	return xxx_messageInfo_OperatingSystem.Size(m)
}
func (m *OperatingSystem) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatingSystem.DiscardUnknown(m)
}

var xxx_messageInfo_OperatingSystem proto.InternalMessageInfo

func (m *OperatingSystem) GetName() OperatingSystemName {
	if m != nil {
		return m.Name
	}
	return OperatingSystemName_UBUNTU
}

func (m *OperatingSystem) GetVersions() []string {
	if m != nil {
		return m.Versions
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.Compliance", Compliance_name, Compliance_value)
	proto.RegisterEnum("api.OperatingSystemFamilyName", OperatingSystemFamilyName_name, OperatingSystemFamilyName_value)
	proto.RegisterEnum("api.OperatingSystemName", OperatingSystemName_name, OperatingSystemName_value)
	proto.RegisterType((*Manifest)(nil), "api.Manifest")
	proto.RegisterMapType((map[string]*Flavor)(nil), "api.Manifest.FlavorsEntry")
	proto.RegisterType((*Flavor)(nil), "api.Flavor")
	proto.RegisterMapType((map[string]*Version)(nil), "api.Flavor.VersionsEntry")
	proto.RegisterType((*Version)(nil), "api.Version")
	proto.RegisterType((*Build)(nil), "api.Build")
	proto.RegisterType((*OperatingSystemFamily)(nil), "api.OperatingSystemFamily")
	proto.RegisterType((*OperatingSystem)(nil), "api.OperatingSystem")
}

func init() { proto.RegisterFile("api/manifest.proto", fileDescriptor_346685e380de5b1f) }

var fileDescriptor_346685e380de5b1f = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x51, 0x6f, 0xd3, 0x3c,
	0x14, 0x5d, 0x92, 0xb6, 0x6b, 0x6f, 0xd7, 0x36, 0x9f, 0xf7, 0x4d, 0x64, 0x45, 0x42, 0x25, 0x12,
	0x52, 0x99, 0x50, 0xd9, 0xca, 0x90, 0x10, 0x6f, 0xdd, 0xd6, 0x42, 0xa4, 0x2d, 0x9d, 0xdc, 0x95,
	0x09, 0xf1, 0x10, 0x79, 0x6d, 0x02, 0x16, 0x4e, 0x1c, 0x25, 0xd9, 0xd0, 0x1e, 0xf8, 0x0d, 0x48,
	0xfc, 0x16, 0x7e, 0x20, 0xaa, 0x63, 0x77, 0x19, 0x4a, 0xdf, 0x6e, 0xce, 0x39, 0x3e, 0xf7, 0xfa,
	0x5c, 0x2b, 0x80, 0x48, 0x4c, 0x5f, 0x87, 0x24, 0xa2, 0x81, 0x9f, 0x66, 0x83, 0x38, 0xe1, 0x19,
	0x47, 0x06, 0x89, 0xa9, 0xfd, 0x47, 0x83, 0xfa, 0x85, 0xc4, 0xd1, 0x4b, 0x30, 0x95, 0xc6, 0xbb,
	0xf3, 0x93, 0x94, 0xf2, 0xc8, 0xd2, 0x7a, 0x5a, 0xbf, 0x81, 0x3b, 0x0a, 0xff, 0x94, 0xc3, 0xe8,
	0x18, 0xb6, 0x03, 0x46, 0xee, 0x78, 0x92, 0x5a, 0x7a, 0xcf, 0xe8, 0x37, 0x87, 0xdd, 0x01, 0x89,
	0xe9, 0x40, 0x59, 0x0d, 0x26, 0x39, 0x39, 0x8e, 0xb2, 0xe4, 0x1e, 0x2b, 0x69, 0xf7, 0x03, 0xec,
	0x14, 0x09, 0x64, 0x82, 0xf1, 0xdd, 0xbf, 0x97, 0x3d, 0x56, 0x25, 0x7a, 0x0e, 0xd5, 0x3b, 0xc2,
	0x6e, 0x7d, 0x4b, 0xef, 0x69, 0xfd, 0xe6, 0xb0, 0x29, 0x5c, 0xf3, 0x33, 0x38, 0x67, 0xde, 0xeb,
	0xef, 0x34, 0xfb, 0xb7, 0x0e, 0xb5, 0x1c, 0x45, 0x08, 0x2a, 0x11, 0x09, 0x7d, 0x69, 0x22, 0x6a,
	0xf4, 0x02, 0xda, 0x01, 0x65, 0x99, 0x9f, 0x78, 0x71, 0xc2, 0x03, 0xca, 0x72, 0xbb, 0x06, 0x6e,
	0xe5, 0xe8, 0x65, 0x0e, 0x22, 0x0b, 0xb6, 0x73, 0x20, 0xb5, 0x8c, 0x9e, 0xd1, 0x6f, 0x60, 0xf5,
	0x89, 0x8e, 0xa0, 0xb9, 0xe0, 0x61, 0xcc, 0x28, 0x89, 0x16, 0x7e, 0x6a, 0x55, 0x7a, 0x46, 0xbf,
	0x3d, 0xec, 0x88, 0x61, 0x4e, 0xd7, 0x38, 0x2e, 0x6a, 0xd0, 0x5b, 0xa8, 0xcb, 0xcc, 0x52, 0xab,
	0x2a, 0x22, 0xd9, 0x2f, 0x0c, 0x3f, 0x90, 0xc1, 0xc9, 0x44, 0xd6, 0xd2, 0xae, 0x03, 0xad, 0x47,
	0x54, 0x49, 0x26, 0xf6, 0xe3, 0x4c, 0x76, 0x84, 0xad, 0x3c, 0x54, 0x0c, 0x65, 0x04, 0xdb, 0x6a,
	0x3d, 0x65, 0xa1, 0xd8, 0x50, 0xbb, 0xb9, 0xa5, 0x6c, 0xa9, 0x36, 0x06, 0xc2, 0xe7, 0x64, 0x05,
	0x61, 0xc9, 0xd8, 0xbf, 0x34, 0xa8, 0x0a, 0x04, 0x61, 0x78, 0xc2, 0x63, 0x3f, 0x21, 0x19, 0x8d,
	0xbe, 0x7a, 0xe9, 0x7d, 0x9a, 0xf9, 0xa1, 0x17, 0x90, 0x90, 0xb2, 0x7c, 0x34, 0xb5, 0xf0, 0xa9,
	0xd2, 0xcc, 0x84, 0x64, 0x22, 0x14, 0x78, 0x8f, 0x97, 0xc1, 0x68, 0x08, 0x7b, 0x4b, 0xfe, 0x23,
	0x62, 0x9c, 0x2c, 0x3d, 0xc6, 0x17, 0x24, 0xa3, 0x3c, 0xf2, 0x6e, 0x13, 0x26, 0xb7, 0xb3, 0xab,
	0xc8, 0x73, 0xc9, 0xcd, 0x13, 0x66, 0xff, 0x84, 0xbd, 0xe9, 0x06, 0xb3, 0x87, 0x2b, 0xb6, 0x87,
	0xcf, 0x36, 0x4f, 0xe3, 0x92, 0xd0, 0x97, 0x11, 0x1c, 0x42, 0x7d, 0xf1, 0x8d, 0xb2, 0x65, 0xe2,
	0x47, 0x32, 0x84, 0xff, 0xcb, 0xce, 0xe1, 0xb5, 0xca, 0xfe, 0x02, 0x9d, 0x7f, 0x48, 0xf4, 0xea,
	0x51, 0x63, 0xab, 0xcc, 0xa0, 0xd0, 0xb2, 0x5b, 0x78, 0x16, 0xba, 0x78, 0x64, 0xeb, 0xef, 0x83,
	0xa7, 0x00, 0x0f, 0xaf, 0x09, 0xb5, 0xa0, 0x31, 0x71, 0x2e, 0x67, 0xde, 0xd1, 0xf1, 0xe1, 0xd0,
	0xdc, 0x3a, 0x08, 0x60, 0x7f, 0xe3, 0x75, 0xd0, 0x7f, 0xd0, 0x3a, 0x1b, 0x9f, 0x38, 0x23, 0xd7,
	0x9b, 0x8c, 0x2e, 0x9c, 0xf3, 0xcf, 0xe6, 0x16, 0xea, 0x40, 0x13, 0x7f, 0x1c, 0x9f, 0x2b, 0x40,
	0x13, 0x9a, 0x11, 0xbe, 0x76, 0xd6, 0x1a, 0x1d, 0x21, 0x68, 0x5f, 0x3b, 0xee, 0xd9, 0xf4, 0x7a,
	0xa6, 0x30, 0xe3, 0xc0, 0x85, 0xdd, 0x92, 0xe9, 0x11, 0x40, 0x6d, 0x7e, 0x32, 0x77, 0xaf, 0xe6,
	0xe6, 0xd6, 0xaa, 0xce, 0xbb, 0x99, 0xda, 0xaa, 0x3e, 0x1d, 0xbb, 0x57, 0xd3, 0x99, 0xa9, 0xa3,
	0x3a, 0x54, 0x56, 0x2d, 0x4d, 0x03, 0x35, 0xa0, 0x7a, 0x31, 0x3a, 0x9d, 0xce, 0xcc, 0xca, 0x4d,
	0x4d, 0xfc, 0x5d, 0xde, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x85, 0x6d, 0x22, 0xd7, 0x73, 0x04,
	0x00, 0x00,
}
